# Generated by Django 5.1.1 on 2024-10-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upass', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
