# Generated by Django 5.1.1 on 2024-11-20 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='login',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_destination',
            field=models.CharField(default='Cit University', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_city',
            field=models.CharField(default='Cit University', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='CitUniversity@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
