# Generated by Django 5.1.1 on 2024-11-19 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_flight_login_user_feedbackform_customersupport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Support'), ('sales', 'Sales'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='booking_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.booking'),
        ),
    ]
