# Generated by Django 5.1.1 on 2024-11-19 14:09

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_customerlog_checkin_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='login',
        ),
        migrations.AddField(
            model_name='checkin',
            name='checkin_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkin',
            name='checkin_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkin',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.flight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkin',
            name='seat_number',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkin',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.booking'),
            preserve_default=False,
        ),
    ]
