# Generated by Django 5.1.1 on 2024-11-20 05:55

import django.utils.timezone
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_checkin_id_remove_checkin_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='flight_id',
        ),
        migrations.AddField(
            model_name='checkin',
            name='booking_reference',
            field=models.CharField(max_length=255, blank=True, null=True),  # Changed to CharField
        ),
        migrations.AlterField(
            model_name='checkin',
            name='checkin_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10),
        ),
    ]
