# Generated by Django 5.1.1 on 2024-11-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_checkin_booking_id_remove_checkin_flight_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
