# Generated by Django 5.1.1 on 2024-11-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_checkin_booking_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckIn',
        ),
    ]
