# Generated by Django 5.1.1 on 2024-11-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('checkin_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(max_length=255)),
                ('checkin_time', models.DateField()),
            ],
        ),
    ]
