# Generated by Django 5.1.1 on 2024-11-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='booking_reference',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='checkin_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
