# Generated by Django 5.1.1 on 2024-11-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_checkin_booking_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='checkin_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='checkin_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
