# Generated by Django 5.1.1 on 2024-11-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_checkin_checkin_id_alter_checkin_checkin_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='checkin_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
