# Generated by Django 5.1.1 on 2024-11-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_checkin_checkin_id'),
    ]

    operations = [
    ]
